sudo: required
services:
  - docker

before_install:
  - docker build -t kingusha/betmelon-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kingusha/betmelon-test npm test -- --coverage

after_success:
  - docker build -t kingusha/betmelon-client ./client
  - docker build -t kingusha/betmelon-server ./server
  - docker build -t kingusha/betmelon-nginx ./nginx
  - docker build -t kingusha/betmelon-postgres ./psqldb
  # Log in docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push kingusha/betmelon-client
  - docker push kingusha/betmelon-server
  - docker push kingusha/betmelon-nginx
  - docker push kingusha/betmelon-postgres
